[[footer]]
name = "Tags"
pageRef = "tags"
weight = 1

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 2

[[footer]]
name = "Status"
url = "https://l01d.openstatus.dev/"
identifier = "vxScehyusI"
weight = 3

[[footer]]
name = "Statistics"
url = "https://cloud.umami.is/share/hgTNxfNOtWvgfRKK/l01d.pages.dev"
identifier = "58kIewLIZI"
weight = 4

[[main]]
none = "none"

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "5ZCkMTWhMu"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "BChxSd7hCX"
weight = 2

[[main]]
name = "GitProfile"
pre = "github"
url = "https://il01di.github.io/gitprofile"
identifier = "fN1CU1GwpY"
weight = 3
