colorScheme = "blowfish"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
disableImageOptimization = false
disableTextInHeader = false
defaultBackgroundImage = "866314.jpg"

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showScrollToTop = true
showAppearanceSwitcher = false

[homepage]
layout = "background"
showRecent = false
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "866314.jpg"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = true
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = ""
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
showZenMode = false
heroStyle = "background"
relatedContentLimit = ""

[list]
showHero = ""
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = ""
showSummary = ""
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = true
heroStyle = "basic"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = false
showHero = false
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]
  # websiteid = "e7836db3-427c-4f49-a3ed-3edfb31dee1a"
  # domain = "l01d.pages.dev"

[buymeacoffee]
  identifier = "L01D"
  globalWidget = true
  globalWidgetMessage = ""
  globalWidgetColor = "#FFDD00"
  globalWidgetPosition = "Right"

[verification]
